font:
  normal:
    family: Fira Code Semibold
  size: 6

# Gruvbox theme
colors:
  primary:
    background: '#282828'
    foreground: '#ebdbb2'

  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
