#!/bin/sh
WALLPAPER_LOCATION=~/Pictures/Wallpapers/wallpaper.jpg

while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                xclip -selection clipboard -target image/png -i < "$file" ;;
        "C-w")
                ln -sf "$file" "$WALLPAPER_LOCATION" && xwallpaper --zoom "$file" ;;
        esac
done
